version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:10.3.2021.22.37.48"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
