version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:10.3.2021.21.0.222"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
