name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 13.1
  POSTGRESQL_DB: amigoscode
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:13.1
#        env:
#          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
#          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
#          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'http://springbootreactfullstack-env.eba-3imjbkem.eu-west-1.elasticbeanstalk.com\n' '${{ job.status }}' === 'success' ? ':white_check_mark:' 'Application deployed' : ':x:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()

#      - uses: actions/checkout@v2
#
#      - uses: actions/setup-java@v1.4.3
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#
#      - name: Maven Clean Package
#        run: |
#          ./mvnw --no-transfer-progress clean package -P build-frontend
#      - uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
#        if: always() # Pick up events even if the job fails or is canceled.
